# Dockerfile for development or testing

FROM python:3.9-slim
WORKDIR /app
COPY . .

RUN pip install poetry==1.1.13
COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi
